# Generated by Django 3.2.3 on 2021-07-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
