# Generated by Django 3.2.3 on 2021-07-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0005_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='Dato no ingresado', max_length=20),
        ),
    ]
