# Generated by Django 3.2.3 on 2021-07-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0006_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='', max_length=999),
        ),
    ]
