# Generated by Django 3.2.3 on 2021-07-19 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakehouse', '0009_alter_compra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='despacho',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='compra',
            name='entrega',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
